train_dataset: fc100
train_dataset_args: {split: train, augment: true, top_k: 3}
fs_dataset: fc100
fs_dataset_args: {split: test, augment: false, top_k: 3}
fs_val_dataset: fc100
fs_val_dataset_args: {split: val, augment: false, top_k: 3}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {avg_pool: true, drop_rate: 0.1, dropblock_size: 2}
    classifier: linear-classifier
    classifier_args: {}

batch_size: 64
max_epoch: 120
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [60, 80]}

save_epoch: 5
visualize_datasets: false


